spring.application.name=service-main
server.port=8888
spring.cloud.config.server.git.uri=spring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.search-paths=config
eureka.client.register-with-eureka=false
eureka.client.fetchRegistry=false
eureka.instance.hostname=localhost
eureka.client.enableSelfPreservation=false